<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestA</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>5b579a76-a33f-479d-9b4d-bcbe1a982fb3</testSuiteGuid>
   <testCaseLink>
      <guid>5c5a5ba7-b34d-4ff7-a0d2-ce8bfe9165e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search Kos By Gender</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>817d14dd-babb-487e-9a31-1bfd7b3abd0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2869dc4-9ec2-4147-8121-ae8d9ad7ced5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
